export const properties = [
    {
      id: 1,
      title: "Luxury Apartment in Downtown Dubai",
      type: "Apartment",
      location: "Downtown Dubai",
      price: 2500000,
      bedrooms: 2,
      bathrooms: 2,
      area: 1200,
      image: "https://example.com/image1.jpg",
      listedDate: "2023-06-15"
    },
    {
      id: 2,
      title: "Spacious Villa in Palm Jumeirah",
      type: "Villa",
      location: "Palm Jumeirah",
      price: 15000000,
      bedrooms: 5,
      bathrooms: 6,
      area: 5000,
      image: "https://example.com/image2.jpg",
      listedDate: "2023-06-10"
    },
    {
      id: 3,
      title: "Modern Studio in Dubai Marina",
      type: "Apartment",
      location: "Dubai Marina",
      price: 800000,
      bedrooms: 0,
      bathrooms: 1,
      area: 500,
      image: "https://example.com/image3.jpg",
      listedDate: "2023-07-01"
    },
    {
      id: 4,
      title: "Penthouse with Burj Khalifa View",
      type: "Penthouse",
      location: "Downtown Dubai",
      price: 20000000,
      bedrooms: 4,
      bathrooms: 5,
      area: 4000,
      image: "https://example.com/image4.jpg",
      listedDate: "2023-05-20"
    },
    {
      id: 5,
      title: "Townhouse in Arabian Ranches",
      type: "Townhouse",
      location: "Arabian Ranches",
      price: 3500000,
      bedrooms: 3,
      bathrooms: 3,
      area: 2200,
      image: "https://example.com/image5.jpg",
      listedDate: "2023-06-25"
    },
    {
      id: 6,
      title: "Beachfront Apartment in JBR",
      type: "Apartment",
      location: "Jumeirah Beach Residence",
      price: 4000000,
      bedrooms: 3,
      bathrooms: 3,
      area: 1800,
      image: "https://example.com/image6.jpg",
      listedDate: "2023-07-05"
    },
    {
      id: 7,
      title: "Luxury Villa in Emirates Hills",
      type: "Villa",
      location: "Emirates Hills",
      price: 40000000,
      bedrooms: 7,
      bathrooms: 8,
      area: 15000,
      image: "https://example.com/image7.jpg",
      listedDate: "2023-04-15"
    },
    {
      id: 8,
      title: "Cozy 1BR in Business Bay",
      type: "Apartment",
      location: "Business Bay",
      price: 1200000,
      bedrooms: 1,
      bathrooms: 2,
      area: 800,
      image: "https://example.com/image8.jpg",
      listedDate: "2023-06-30"
    },
    {
      id: 9,
      title: "Spacious 3BR in Dubai Hills Estate",
      type: "Apartment",
      location: "Dubai Hills Estate",
      price: 3000000,
      bedrooms: 3,
      bathrooms: 3,
      area: 1600,
      image: "https://example.com/image9.jpg",
      listedDate: "2023-07-10"
    },
    {
      id: 10,
      title: "Waterfront Villa in Palm Jebel Ali",
      type: "Villa",
      location: "Palm Jebel Ali",
      price: 12000000,
      bedrooms: 4,
      bathrooms: 5,
      area: 4500,
      image: "https://example.com/image10.jpg",
      listedDate: "2023-05-01"
    },
    {
      id: 11,
      title: "Duplex Penthouse in Marina",
      type: "Penthouse",
      location: "Dubai Marina",
      price: 8000000,
      bedrooms: 3,
      bathrooms: 4,
      area: 3000,
      image: "https://example.com/image11.jpg",
      listedDate: "2023-06-20"
    },
    {
      id: 12,
      title: "Affordable Studio in International City",
      type: "Apartment",
      location: "International City",
      price: 300000,
      bedrooms: 0,
      bathrooms: 1,
      area: 400,
      image: "https://example.com/image12.jpg",
      listedDate: "2023-07-15"
    },
    {
      id: 13,
      title: "Family Villa in The Meadows",
      type: "Villa",
      location: "The Meadows",
      price: 7000000,
      bedrooms: 5,
      bathrooms: 5,
      area: 3800,
      image: "https://example.com/image13.jpg",
      listedDate: "2023-05-10"
    },
    {
      id: 14,
      title: "2BR Apartment with Dubai Creek View",
      type: "Apartment",
      location: "Dubai Creek Harbour",
      price: 2200000,
      bedrooms: 2,
      bathrooms: 2,
      area: 1100,
      image: "https://example.com/image14.jpg",
      listedDate: "2023-06-05"
    },
    {
      id: 15,
      title: "Townhouse in Jumeirah Village Circle",
      type: "Townhouse",
      location: "Jumeirah Village Circle",
      price: 1800000,
      bedrooms: 3,
      bathrooms: 3,
      area: 1900,
      image: "https://example.com/image15.jpg",
      listedDate: "2023-07-20"
    },
    {
      id: 16,
      title: "Luxurious 4BR Penthouse in DIFC",
      type: "Penthouse",
      location: "Dubai International Financial Centre",
      price: 25000000,
      bedrooms: 4,
      bathrooms: 5,
      area: 5000,
      image: "https://example.com/image16.jpg",
      listedDate: "2023-04-25"
    },
    {
      id: 17,
      title: "Cozy 1BR in Motor City",
      type: "Apartment",
      location: "Motor City",
      price: 700000,
      bedrooms: 1,
      bathrooms: 1,
      area: 700,
      image: "https://example.com/image17.jpg",
      listedDate: "2023-07-08"
    },
    {
      id: 18,
      title: "Beachfront Villa in Pearl Jumeirah",
      type: "Villa",
      location: "Pearl Jumeirah",
      price: 30000000,
      bedrooms: 6,
      bathrooms: 7,
      area: 8000,
      image: "https://example.com/image18.jpg",
      listedDate: "2023-05-15"
    },
    {
      id: 19,
      title: "2BR Apartment in Al Barsha",
      type: "Apartment",
      location: "Al Barsha",
      price: 1500000,
      bedrooms: 2,
      bathrooms: 2,
      area: 1000,
      image: "https://example.com/image19.jpg",
      listedDate: "2023-06-28"
    },
    {
      id: 20,
      title: "Stylish Loft in d3",
      type: "Apartment",
      location: "Dubai Design District",
      price: 2800000,
      bedrooms: 1,
      bathrooms: 2,
      area: 1300,
      image: "https://example.com/image20.jpg",
      listedDate: "2023-07-03"
    },
    {
      id: 21,
      title: "Waterfront Townhouse in Dubai Creek Harbour",
      type: "Townhouse",
      location: "Dubai Creek Harbour",
      price: 4500000,
      bedrooms: 4,
      bathrooms: 4,
      area: 2500,
      image: "https://example.com/image21.jpg",
      listedDate: "2023-05-30"
    },
    {
      id: 22,
      title: "Penthouse with Panoramic Views in Marina",
      type: "Penthouse",
      location: "Dubai Marina",
      price: 18000000,
      bedrooms: 5,
      bathrooms: 6,
      area: 6000,
      image: "https://example.com/image22.jpg",
      listedDate: "2023-06-12"
    }
  ];